apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${AWS_ECR_ACCOUNT_URL}/circle-demo-react-${VERSION}
  namespace: default
  labels:
    app: ${AWS_ECR_ACCOUNT_URL}/circle-demo-react
    version: "${VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${AWS_ECR_ACCOUNT_URL}/circle-demo-react
      version: "${VERSION}"
  template:
    metadata:
      labels:
        app: ${AWS_ECR_ACCOUNT_URL}/circle-demo-react
        version: "${VERSION}"
    spec:
      containers:
      - name: ${AWS_ECR_ACCOUNT_URL}/circle-demo-react
        imagePullPolicy: Always
        image: ${AWS_ECR_ACCOUNT_URL}/circle-demo-react-${VERSION}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi