version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello_build
  
  lint:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello_build
  
  acceptance_test_1:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello test one
  
  acceptance_test_2:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello test two

  acceptance_test_3:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello test three

  acceptance_test_4:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello test four

  build_docker_push_ecr:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello_build

  deploy:
    docker:
      - image: cimg/base:edge-18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo hello test one

workflows:
  build_accept_deploy:
    jobs:
      - build
      - lint
      - acceptance_test_1:
          requires:
            - build
            - lint
      - acceptance_test_2:
          requires:
            - build
            - lint
      - acceptance_test_3:
          requires:
            - build
            - lint
      - acceptance_test_4:
          requires:
            - build
            - lint
      - build_docker_push_ecr:
          requires: 
            - acceptance_test_1
            - acceptance_test_2
            - acceptance_test_3
            - acceptance_test_4
      - hold:
          type: approval 
          requires: 
            - build_docker_push_ecr
      - deploy:
          requires:
            - hold