# indicated what version of circleci is running. Essential to state this due to feature updates etc
version: 2.1

# Orbs are a prepared package that contains reusable CircleCI config that can be used across projects
# Using the Herouku orb that has jobs such as heroku/deploy-via-git 
# orbs:
#   heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb
orbs:
    node: circleci/node@3.0.1
    aws-ecr: circleci/aws-ecr@6.12.0
    heroku: circleci/heroku@1.2.6
    helm: circleci/helm@1.2.0
    aws-eks: circleci/aws-eks@1.0.0
    k-connect: db-cci-ns/k-connect@0.5.0

executors:
  node:
    docker: 
      - image: cimg/node:14.0.0
workflows:
  build_CCI:
    jobs:
      - build
      - unit_tests:
          requires: 
            - build
      - kconnect:
          context: rp-deploy-secrets
      - aws-ecr/build-and-push-image:
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          attach-workspace: true
          context: rp-deploy-secrets
          account-url: AWS_ECR_ACCOUNT_URL
          name: build_push_ecr
          repo: circle-demo-react
          tag: $CIRCLE_SHA1
          requires:
            - unit_tests
      - hold_eks:
          type: approval
          requires:
            - build_push_ecr
      - helm_eks:
          context: rp-deploy-secrets
          requires:
            - hold_eks

# Collection of steps to run in a CCI build process. We have one job here - build. Build has 6 steps
# The heroku orb will also add another job - heroku/deploy-via-git
jobs:
  build:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: CYPRESS_INSTALL_BINARY=0 npm ci
  
  unit_tests:
    docker:
      - image: cimg/node:14.0.0
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - node-cache-v1-{{ .Branch }}-
              - node-cache-v1-
      - run:
          name: Fetch dependencies
          command: npm ci
      - save_cache:
          paths:
              - ~/.npm
              - ~/.cache
          key: node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Test application 
          command: |
            TEST=$(circleci tests glob **/src/**/*.test.js | circleci tests split --split-by=timings)
            npm test $TEST
  
  kconnect:
    docker:
      - image: 'cimg/base:2021.04'
    environment:
      AWS_ACCESS_KEY_ID: ASIAZTZQYRUZPGRUGS5E
      AWS_SECRET_ACCESS_KEY: UsLsQGsyCicp+f0RAaXIgQVcGxM+njatKLvVtxvk
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEG4aCXVzLWVhc3QtMSJGMEQCIAFVmc/HQgwRAoR/jV1WrW3iK9sRfNK9yaNzmJAQOAbeAiAi3KdKaoO5NP3hlI1vuYCxjbgrSobehCG0fQDZFHx3kiqXAwin//////////8BEAIaDDY2MDk5MDM2NDk3OCIMTXsoICschMgUN14nKusCy1+8bVIODxuwBTfOit4jfjtHo8cvV7/6XwJoX3LaMAyoWOc81r49tbgyhtibC+rc0dXeD8HIuDblFfB6lIynFe7ZKfAelXOwc9BEoBE/GX6EkEjJUVlRxZBN6sfRWD2wPbkhuAG5iwgUWBPYbEuIvfVHnYiHta2qE8lnnjHHOeufaqEtnRxvqqU16efa7KNIHLnC4O0MQJp/OmC6RA4IWJux+GmN5w+PbuoUyHw34bTx4YWOc0XFP3EKqIpCwdyYOL1J7YjsLV/kOpIRYSjBhBiW2Z9K4hSC9+93AayXPI0xgt4o3hTrAdeKCykRIBDY0FG+To3Xl/ruHe3M3UAIHJKiMJEk/zPeJ/jFZ+FskTE37g7TTtzXY6DhoIXQM2GddYj0aK2ZTXFmVy5pu4HRUPfYjjeLGfPoLmC9jVnHr+18XS/jFOxhEPK97cwN+yARDjYfRrgdeMlcj33lu7HbxdH6CZhCRsvaAi18MNqA+o8GOqcBQgg4nRDRHMdrMYvjYcMmAXvccnNuWx8UBWPy0EvJg7Ny4eJYFQiAbGxyweRJccr9IlzRR8mSEO97mCkPFI62NpKjrpWJ/mcmWNlo93kT9CFV66xcd5hrjkC0nMuSV7Y5aKWTe13aBWiUN3Ola+pcSjjuZgnSm0oWgzagBpIpNNZvVkqEWeXeklqFj9or0RbMscbk0qSPxHh3H7RliDZEO4Vp28U+Kd0=
    steps:
      - checkout
      - k-connect/install
      - k-connect/configure:
          config_file_path: >-
            https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml
      - k-connect/use:
          alias: eks-test-kconnect
          cluster_id: 'arn:aws:eks:eu-west-1:660990364978:cluster/db-demo-cluster'
          cluster_provider: eks
      - run:
          command: kubectl get all
          name: Test kconnect connection
      - k-connect/to:
          alias: eks-test-kconnect
      - k-connect/ls
      - k-connect/version
      
  helm_eks:
    docker:
      - image: circleci/python:3.7
    environment:
      IMAGE: ${AWS_CONTAINER_ID}
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${EKS_CLUSTER_NAME}
          aws-region: ${AWS_REGION}
          install-kubectl: true
          verbose: true
      - helm/install-helm-client:
          version: v3.0.0
      - helm/upgrade-helm-chart:
          chart: ./helm-charts/react-app-chart
          release-name: react-app-chart-1620714714
          values-to-override: image.tag=${CIRCLE_SHA1},image.repository=${AWS_CONTAINER_ID}

  
  # build:
  #   docker:
  #       - image: cimg/node:12.16
  #   parallelism: 5
  #   steps:
  #       - checkout
  #       - node/install-packages:
  #           pkg-manager: yarn      
  #       - run: mkdir ~/junit
  #       - run:
  #           name: Test application
  #           command: |
  #               TEST=$(circleci tests glob **/__tests__/*.js | circleci tests split --split-by=timings)
  #               yarn test 
  #       - run:
  #           command: cp junit.xml ~/junit/
  #           when: always
  #       - store_test_results:
  #           path: ~/junit
  #       - store_artifacts:
  #           path: ~/junit


  # build:
  #   docker:
  #     - image: circleci/node:12.9.1-browsers
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run: 
  #         name: mkdir for test results
  #         command: mkdir ~/test-results
  #     - run:
  #         name: Update NPM
  #         command: "sudo npm install -g npm@5"
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: Install Dependencies
  #         command: npm install
  #     - save_cache:
  #         paths:
  #           - ./node_modules
  #           - ~/.npm
  #           - ~/.cache
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: Run tests 
  #         command: |
  #           TEST=$(circleci tests glob **/__tests__/*.js | circleci tests split)
            
  #           npm test $TEST -o ~/test-results
  #     - store_test_results:
  #         path: ~/test-results
  #     - run:
  #         echo "${CIRCLE_BRANCH}"