apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-webapp
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-webapp
    spec:
      containers:
        - name: webapp
          image: 660990364978.dkr.ecr.eu-west-1.amazonaws.com/rp-se-demo/circle-demo-react:cf437266b2edf1f2d86ddca889eb677c934d0063
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 80
status: {}



# image: 660990364978.dkr.ecr.eu-west-1.amazonaws.com/rp-se-demo/circle-demo-react:d83ca9096d717cef82a68eb6743bb393750d2c4d
